name: CI Spring Boot

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target/

      - name: Get current date
        run: echo "IMAGE_TAG=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t smartnews:$IMAGE_TAG .
          docker tag smartnews:$IMAGE_TAG smartnews:latest
          docker tag smartnews:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/smartnews:$IMAGE_TAG
          docker tag smartnews:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/smartnews:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/smartnews:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/smartnews:latest
